[tox]
envlist =
    py{311}-django{42,52},
    py311-codestyle

[testenv]
setenv =
    PYTHONDONTWRITEBYTECODE=1
; install_command = pip install --no-deps {opts} {packages}
deps =
    django42: Django>=4.2,<5.0
    django52: Django>=5.2,<6.0
    -rrequirements.txt
commands = python runtests.py {posargs}

[testenv:py311-codestyle]
deps = -rrequirements.txt
commands =
    black -S nexus tests runtests.py setup.py
    isort nexus tests runtests.py setup.py
    flake8
